spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: secret
  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret:
            scope:
              - email
              - profile
mail:
  address:
    admin: admin@gmail.com
jwt:
  key:
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420